# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-07 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0003_auto_20161007_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
