# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0005_gallary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='upload_image',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
